from enum import IntEnum


class ApiMessageCode(IntEnum):

    SUCCESS = 0

    PAYLOAD_CREATION_FAILED = 101
    PAYLOAD_EXPIRED = 102
    PAYLOAD_NOT_FOUND = 103

    TON_PROOF_GETTING_PUBLIC_KEY_FAILED = 111
    TON_PROOF_PUBLIC_KEYS_MISMATCH = 112
    TON_PROOF_SIGNATURE_VERIFICATION_FAILED = 113
    TON_PROOF_EXPIRED = 114

    TON_DEX_ASSET_NOT_FOUND = 121
    TON_DEX_POOL_NOT_FOUND = 122
    TON_DEX_ERROR_GETTING_LIQUIDITY_PARAMS = 123
    TON_DEX_ERROR_PREPARING_CREATE_POOL = 124
    TON_DEX_ERROR_PREPARING_PROVIDE_LIQUIDITY = 125
    TON_DEX_ERROR_PREPARING_PROVIDE_SINGLE_SIDE = 126
    TON_DEX_ERROR_PREPARING_ACTIVATE_LIQUIDITY = 127
    TON_DEX_ERROR_PREPARING_REMOVE_LIQUIDITY = 128
    TON_DEX_ERROR_PREPARING_REFUND = 129
    TON_DEX_ERROR_PREPARING_SWAP = 133
    TON_DEX_ERROR_GETTING_SWAP_PARAMS = 134

    INVALID_TON_ADDRESS = 131
    ACCOUNT_NOT_FOUND = 132
